# Site settings
title: GeoCenter analysis & visualization resources
email: geocenter@usaid.gov
description: > # this means to ignore newlines until "baseurl:"
  An intro into the fundamentals of data analysis and visualization using Stata
baseurl:  /resources
url:  geocenter.github.io # the base hostname & protocol for your site
twitter_username: usaidgeo
github_username:  geocenter

# Build settings
markdown: kramdown

# highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  visresources:
    output: true
  poetry:
    output: true
    permalink: /poetry/:path/
